### ISSUE TITLE
Do Javascript something

### ISSUE THREAD

**Issue by jaehafe** [zoumadeng1/gitflow-prac2#1]
## 설명

for와 if를 이용해 Javascript 무언가를 수행하겠습니다.

## Tasks

- [x] Do something of 'for' statement
- [x] Do something of 'if' statement
- [x] Do something of 'array' statement

**Comment by jaehafe1** [comment]
네 좋습니다.

**Comment by jaehafe1** [comment]
done by jaehafe
